### PR TITLE
Some usability improvements

### PR DESCRIPTION
**Pull request by antonverburg**
Hi Dennis, 

Here a proposal for some usability improvements on your PID controller. It's my intention to integrate the controller in HomeAssistant, but in it's current state I miss some functions and some parts can be easier for a cleaner interface. Are you willing to add these modifications to your controller, and create an update of the PIP package for that?

Kind regards, Anton

### CODE REVIEW

**Comment by antonverburg** [comment]
By the way: I am actually testing the code, so please don't merge immediately. Better wait if more modifications and/or improvements are required for a while...

**Comment by Dennis-van-Gils** [comment]
Dear Anton, Thanks for your interest in the PID controller. I suggest you create a fork and modify it for yourself, privately. My code at work relies on this package, using `np.nan` above `None` as it has clear benefits when performing maths. Best, Dennis

**Comment by antonverburg** [comment]
Hi Dennis, what if I keep the np.Nan, are you interested in the other mods? Personally I prefer not to fork...

**Comment by Dennis-van-Gils** [comment]
I could add in the differential input argument, but could you please explain me the use-case for this option? In my opinion there is no such thing as differential input to a PID controller. If you still need it, you simply pass the subtraction as argument parameter to method `compute()`

I can make `error` accessible, that's easy and does not break anything.

**Comment by Dennis-van-Gils** [comment]
_I can make `error` accessible, that's easy and does not break anything._
Done, see PyPi v2.0.1 https://pypi.org/project/dvg-pid-controller/

**Pull request closed without merging**
